version: "3.8"
services:
  gatsby-fork:
    build:
      context: ./docker/gatsby-fork
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - type: bind
        source: ./gatsby-fork
        target: /home/node/workdir
    user: node
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
